Move Tabs, Minio disk usage and parameters button in the top bar
farao-community/gridcapa-app pull request #128
Opened 2024-06-24 10:57 UTC by oualid-aloui-rte

![Capture d’écran de 2024-06-13 00-48-46](https://github.com/farao-community/gridcapa-app/assets/116628858/2f1a118e-c117-42a4-a4d8-e5943c57f899)
![Capture d’écran de 2024-06-13 00-48-51](https://github.com/farao-community/gridcapa-app/assets/116628858/ecc71a3b-ff2c-4c76-ad01-32857c75d580)
![Capture d’écran de 2024-06-13 00-49-03](https://github.com/farao-community/gridcapa-app/assets/116628858/126b0018-b71f-4e6e-bdd5-fa012131c17a)

2024-06-24 12:07 UTC, schwitzguebel commented
When on login page we see the header menu, is this normal ?

2024-06-27 13:19 UTC, kahyami requested changes

2024-06-27 13:19 UTC, kahyami commented on src/utils/view-utils.js
> +            // in the Business View is the same as the one given in parameter.
in the Business Date View

2024-06-27 13:19 UTC, kahyami commented on src/components/minio-disk-usage.js
> +import React, { useEffect, useState } from 'react';
add Copyright

2024-06-28 07:57 UTC, kahyami approved these changes

2024-06-28 07:57 UTC, merged