add business date view
farao-community/gridcapa-app pull request #23
Opened 2022-02-18 09:42 UTC by kahyami

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
The business date view is not implemented

**What is the new behavior (if this is a feature change)?**
Add the business date view

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*
No

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-02-18 16:59 UTC, WalAmeni submitted a review, later dismissed

2022-02-18 17:13 UTC, TheMaskedTurtle requested changes

2022-02-18 17:13 UTC, TheMaskedTurtle commented on src/components/overview-table-business-view.js
> +};
Can you use the same color code as we defined in table-header.js to define the color of the status chip ?

2022-02-21 13:54 UTC, TheMaskedTurtle requested changes

2022-02-21 14:09 UTC, merged