Predifined filter for timestamp
farao-community/gridcapa-app pull request #66
Opened 2022-08-10 10:52 UTC by titus6012000

**MUST BE REVIEWED AFTER THE PULL REQUEST ON UPLOAD FILE HAS BEEN MERGED**

Add a configured predefined filter on the timestamp column in the business date view

2022-08-12 08:52 UTC, kahyami requested changes

2022-08-16 09:32 UTC, titus6012000 commented on src/components/filter-menu.js
> +        let boxfilter = [...selectedFilter];
boxfilter renamed to box**F**ilter

2022-08-16 09:33 UTC, titus6012000 commented on src/components/global-view-core.js
> +        // gridcapaFormatDate is not accessible inside the filter we have to use an intermediaire
wording reviewed

2022-08-16 09:35 UTC, titus6012000 commented on src/components/filter-menu.js
> +            predefinedValues.forEach((filtre, filterIndex) => {
filtre renamed to filt**er**

2022-08-16 09:38 UTC, titus6012000 commented on src/components/global-view-core.js
> +                                        fixedFilter.length > 0 ? false : true
yes you're right

2022-08-16 09:40 UTC, titus6012000 commented on src/components/global-view-core.js
> +        let newFilter = filtres.map((filtre) => filtre.toUpperCase());
the four occurrences of filtres has been renamed 
and
the four occurrences of filtre has been renamed

2022-09-02 08:31 UTC, TheMaskedTurtle approved these changes

2022-09-02 08:32 UTC, merged